library(devtools)
library(shiny)
library(stringr)
library(roxygen2)

# alternatively; use Shiny to make R/ folder with functions made from inputs, provide instructions for including them into a package
# create_package and use_course

ui <- fluidPage(

    
    titlePanel("Create a package"),

    numericInput("num", label = h3("Add this number"), value = 1),
    
    textInput("packageName", label = h3("Enter a name for your package"), value = "A.Package"),
    
    textInput("author", label = h3("Enter your name"), value = "Ian Dinnie"),
    
    textInput("email", label = h3("Enter your email address"), value = "test@email.com"),
    
    actionButton("action", label = "Create Package")
)

server <- function(input, output) {

  observeEvent(input$action, {
    
    # currently unsure how to use temp directory to create package
    td <- tempdir()
    dir.create(paste0(td, "/", input$packageName))
    dir.create(paste0(td, "/", input$packageName, "/R"))
    fileConn <- file(paste0(td, "/", input$packageName, "/R/myFunction.R"))
    writeLines(paste0("#' A test function
                      #'
                      #' @param x A numeric input to add to
                      #' 
                      #' @return The sum of x and ", input$num,"
                      #' @export
                      #'
                      #' @examples
                      #' x <- 1
                      #' myFunction(x)
                      myFunction <- function(x) x + ", input$num), fileConn)
    setwd(paste0(td, "/", input$packageName))
    usethis::proj_set(paste0(td, "/", input$packageName), force = T)
    use_description(
      fields = list(
        Package = input$packageName,
        Title = paste0("A package that was generated by a shiny app"),
        # this authors section doesn't currently work, unsure how important that is
        # so I'm populating it with my own name and email
        `Authors@R` = person("Ian", "Dinnie", , "ian.dinnie@posit.co", role = c("aut", "cre")),
          # paste0('person("', unlist(stringr::str_split(input$author, " "))[1],'", ',unlist(stringr::str_split(input$author, " "))[2],'", , "',input$email,'", role = "aut")'),
        Description = paste0("Proof that packages can be built from shiny apps!"),
        License = "`use_mit_license()`",
        Encoding = "UTF-8",
        Roxygen = "list(markdown = TRUE)",
        RoxygenNote = "7.2.1"
        
      )
    )
    
    use_mit_license()
    document()
    roxygenize()
    devtools::check()
    build(binary = F)
    install()
    
  })
  
  

}


# This is somewhat a proof-of-concept,
# the above app will take in user input, create a function and store into a package (with a few caveats (see comments))
# it then successfully loads into the user's environment and we can use that function as expected
# we now need to figure how to get the tar.gz out of the temp memory and make it accessible to the user to share via whatever package manager they want to use
# I also have to restart my R session before every 'Run App' call; how do we handle this on Connect?
# Also want to make sure the temp directory is erased after package is completely built, similar to above question

# Run the application 
shinyApp(ui = ui, server = server)
